import type { Metadata } from "next";
import { Roboto, Marcellus ,Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import Script from "next/script";
import Footer from "./components/footer";
import Header from "./components/header";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const marcellus = Marcellus({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${marcellus.className} ${poppins.className}`}>
        <Header/>
        <main className="main">
              {children}

        </main>
        <Footer/>

        <Script src="/assets/js/main.js"></Script>
      </body>
    </html>
  );
}
